#!/usr/bin/env bash

PARENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

TX_VK="$(base64 < "$PARENT_DIR"/../params/transfer_verification_key.bin)"
TREE_VK="$(base64 < "$PARENT_DIR"/../params/tree_verification_key.bin)"

near dev-deploy --wasmFile out/main.wasm && \
source neardev/dev-account.env && \
near call $CONTRACT_NAME new '{"owner_id": "'$CONTRACT_NAME'", "total_supply": "1000000000000000", "metadata": { "spec": "ft-1.0.0", "name": "ZeroPool Test Token", "symbol": "ZPTS", "decimals": 8 }, "tx_vk": "'$TX_VK'", "tree_vk": "'$TREE_VK'", "denominator": "100000000"}' --accountId $CONTRACT_NAME
