#!/usr/bin/env bash

PARENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
TOKEN_ID=${2:-"near"}

"$PARENT_DIR"/build && \
near dev-deploy --wasmFile "$PARENT_DIR"/../out/main.wasm \
  --initArgs "{\"token_id\": \"$TOKEN_ID\", \"denominator\": \"100000000\" }"